Hiperparâmetros de uma Rede Neural
* LOSS: função de perda para avaliação do erro (ex.: `mean_squared_error`).
* Optimizer: otimizador de ajuste de pesos da rede. Adam (stochastic gradient desent).
* Metrics: métrica utilizada para avaliar o desempenho da rede.

In [1]:
# Importação das bibliotecas
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.feature_extraction.text import CountVectorizer
from keras.models import Sequential   # conjunto de camadas sequenciais
from keras.layers import Dense, Dropout

In [2]:
# Importação do arquivo
from google.colab import files
uploaded = files.upload()

Saving spam.csv to spam.csv


In [3]:
# Criação um objeto dataframe
spam = pd.read_csv('spam.csv')
spam.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
# Exibição da dimensão do dataframe
spam.shape

(5572, 2)

In [5]:
# Exibição do número de elementos de cada categoria
spam.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [10]:
# Transformação da coluna categoria em número (variável dependente)
labelencoder = LabelEncoder()
y = labelencoder.fit_transform(spam['Category'])
y

array([0, 0, 1, ..., 0, 0, 0])

In [12]:
# Variável independente
mensagens = spam['Message'].values      # transformação do objeto do pandas em objeto do numpy

# Divisão dos dados em treino e teste
X_train, X_test, y_train, y_test = train_test_split(mensagens, y, test_size = 0.3)

In [13]:
# Vetorização das mensagens
vetorizador = CountVectorizer() # Criação do objeto
vetorizador.fit(X_train)        # Criação do modelo
X_train = vetorizador.transform(X_train)
X_test = vetorizador.transform(X_test)

In [15]:
# Nº de features (a camada de entrada tem que ter 1 neurônio para cada feature)
X_train.shape[1]

7221

In [16]:
# Montagem da arquitetura da rede neural
modelo = Sequential()                                                         # Criação de uma variável modelo com o objeto Sequential instanciado (para iniciar a montagem das camadas)
modelo.add(Dense(units=10, activation='relu', input_dim=X_train.shape[1]))    # Montagem da 1ª camada (camada densa)
                                                                              # units=10 :: nº de neurônios (escolha arbitrária)
                                                                              # activation='relu' :: função de ativação
                                                                              # input_dim=X_train.shape[1] :: nº de neurônios da camada de entrada (tem que ter 1 neurônio para cada feature)
                                                                              # input_dim entra somente na 1ª camada

modelo.add(Dropout(0.1))                                                      # Montagem da camada de dropout (evita overfitting)
                                                                              # Remove algumas sinapses (conexões entre neurônios de camadas diferentes)

modelo.add(Dense(units=8, activation='relu'))                                 # Montagem da 2ª camada densa
                                                                              # A escolha do nº de neurônios (units=8) também foi arbitrária

modelo.add(Dropout(0.1))                                                      # Montagem da camada de dropout (evita overfitting)

modelo.add(Dense(units=1, activation='sigmoid'))                              # Montagem da camada de saída
                                                                              # A escolha do nº de neurônios corresponde ao número de saídas
                                                                              # units=1 :: retorna 1 valor que é a probabilidade entre 0 e 1

In [18]:
# Compilação do modelo
modelo.compile(loss="mean_squared_error", optimizer="adam", metrics=["accuracy"])
modelo.summary()

# loss: função de perda (diferença entre o que foi previsto e o que foi observado)
# optimizer: função que otimiza o ajuste dos pesos
# backpropagation: processo de ajuste da rede
# metrics: métrica utilizada para avaliação do desempenho da rede

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                72220     
                                                                 
 dropout (Dropout)           (None, 10)                0         
                                                                 
 dense_1 (Dense)             (None, 8)                 88        
                                                                 
 dropout_1 (Dropout)         (None, 8)                 0         
                                                                 
 dense_2 (Dense)             (None, 1)                 9         
                                                                 
Total params: 72317 (282.49 KB)
Trainable params: 72317 (282.49 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [19]:
# Treinamento da rede neural
modelo.fit(X_train, y_train, epochs=20, batch_size=10, verbose=True, validation_data=(X_test, y_test))

# Todos os registros de X_train serão passadas pela rede a cada epoch
# epoch: nº de vezes que o modelo é executado
# batch_size: nº de exemplos de treinamento usados a cada iteração do modelo
# verbose=True :: fornece feedback interativo a cada processo de treinamento
# validation_date: dados de teste

Epoch 1/20
390/390 [==============================] - 4s 7ms/step - loss: 0.0694 - accuracy: 0.9369 - val_loss: 0.0169 - val_accuracy: 0.9850
Epoch 2/20
390/390 [==============================] - 3s 8ms/step - loss: 0.0101 - accuracy: 0.9887 - val_loss: 0.0127 - val_accuracy: 0.9862
Epoch 3/20
390/390 [==============================] - 2s 5ms/step - loss: 0.0051 - accuracy: 0.9944 - val_loss: 0.0122 - val_accuracy: 0.9862
Epoch 4/20
390/390 [==============================] - 1s 4ms/step - loss: 0.0032 - accuracy: 0.9956 - val_loss: 0.0121 - val_accuracy: 0.9862
Epoch 5/20
390/390 [==============================] - 2s 4ms/step - loss: 0.0023 - accuracy: 0.9967 - val_loss: 0.0121 - val_accuracy: 0.9862
Epoch 6/20
390/390 [==============================] - 2s 5ms/step - loss: 0.0015 - accuracy: 0.9987 - val_loss: 0.0125 - val_accuracy: 0.9856
Epoch 7/20
390/390 [==============================] - 1s 4ms/step - loss: 0.0013 - accuracy: 0.9992 - val_loss: 0.0125 - val_accuracy: 0.9862
Epoch 

In [20]:
# Métricas de avaliação do modelo
loss, accuracy = modelo.evaluate(X_test, y_test)

53/53 [==============================] - 0s 3ms/step - loss: 0.0129 - accuracy: 0.9844


In [21]:
# Previsão de novas mensagems
nova_previsao = modelo.predict(X_test)
nova_previsao

# Como foi usada a função de ativação sigmoid na camada de saída, a previsão é um número entre 0 e 1

53/53 [==============================] - 1s 3ms/step


array([[7.1052270e-04],
       [1.0530327e-01],
       [6.5223110e-05],
       ...,
       [1.9500286e-09],
       [4.8450278e-05],
       [9.9999988e-01]], dtype=float32)

In [23]:
# Mostrando as classes que foram previstas
prev = (nova_previsao > 0.5)
prev

# Valor True :: a mensagem é classificada como spam
# Valor False :: a mensagem não é classificada como spam

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [ True]])

In [24]:
# Matriz de confusão
confusion_matrix(y_test, prev)

array([[1431,    6],
       [  20,  215]])